(function () {
  window.PromptTemplates = [
    { name:'Ajuste de layout', type:'visual', desiredChange:'Reorganizar os elementos da tela para ocupar menos espaço.', currentBehavior:'Os elementos estão desalinhados e o bloco ocupa muita altura.', expectedResult:'Os elementos devem ficar organizados no computador e se adaptar ao celular.', preserve:'Manter todos os comandos e o padrão visual existente.' },
    { name:'Correção de bug', type:'bug', desiredChange:'Corrigir um comportamento incorreto no fluxo atual.', currentBehavior:'O fluxo apresenta um erro durante a operação.', expectedResult:'A operação deve terminar corretamente, com mensagens claras em caso de falha.', preserve:'Não alterar outros fluxos nem dados existentes.' },
    { name:'Criação de nova tela', type:'feature', desiredChange:'Criar uma nova tela seguindo o projeto atual.', currentBehavior:'Essa operação ainda não possui uma tela própria.', expectedResult:'A tela deve permitir concluir a operação e funcionar em computador e celular.', preserve:'Manter navegação, permissões e padrão visual atuais.' },
    { name:'Criação de dashboard', type:'feature', desiredChange:'Criar um dashboard com os indicadores principais.', currentBehavior:'As informações estão dispersas e exigem consultas separadas.', expectedResult:'Os indicadores devem aparecer com clareza, filtros e estados de carregamento.', preserve:'Não alterar a origem nem a precisão dos dados atuais.' },
    { name:'Integração com Google Sheets', type:'integration', desiredChange:'Integrar o projeto com uma planilha do Google Sheets.', currentBehavior:'Os dados são transferidos manualmente.', expectedResult:'Os dados devem ser sincronizados com tratamento de falhas e logs úteis.', preserve:'Não expor credenciais nem interromper o fluxo atual.' },
    { name:'Autenticação Google', type:'security', desiredChange:'Adicionar login seguro com conta Google.', currentBehavior:'O acesso atual não utiliza autenticação Google.', expectedResult:'Usuários autorizados devem entrar com segurança e receber as permissões corretas.', preserve:'Manter os usuários e perfis existentes compatíveis.' },
    { name:'Importação de planilha', type:'feature', desiredChange:'Permitir a importação de dados por planilha.', currentBehavior:'Os dados precisam ser cadastrados manualmente.', expectedResult:'O arquivo deve ser validado e erros devem ser informados por linha.', preserve:'Não duplicar nem sobrescrever dados válidos sem confirmação.' },
    { name:'Criação de relatório', type:'feature', desiredChange:'Criar um relatório com filtros e exportação.', currentBehavior:'Não existe uma visão consolidada desses dados.', expectedResult:'O relatório deve exibir dados corretos e preservar filtros na exportação.', preserve:'Não alterar consultas e relatórios existentes.' },
    { name:'Alteração de banco de dados', type:'database', desiredChange:'Adaptar a estrutura de dados para armazenar novas informações.', currentBehavior:'A estrutura atual não contempla os dados necessários.', expectedResult:'A alteração deve preservar registros e permitir rollback.', preserve:'Não perder dados nem quebrar consultas existentes.' },
    { name:'Publicação no GitHub Pages', type:'deploy', desiredChange:'Publicar o projeto estático no GitHub Pages.', currentBehavior:'O projeto funciona apenas localmente.', expectedResult:'O site deve abrir em uma URL pública com caminhos funcionando.', preserve:'Manter o funcionamento local e não expor informações sensíveis.' },
    { name:'Publicação na Hostinger', type:'deploy', desiredChange:'Publicar o projeto na Hostinger.', currentBehavior:'O projeto ainda não está disponível no ambiente final.', expectedResult:'O sistema deve ficar acessível com HTTPS e processo de rollback.', preserve:'Não interromper o ambiente atual sem plano de retorno.' },
    { name:'Novo sistema', type:'new-system', desiredChange:'Criar um novo sistema a partir desta necessidade.', currentBehavior:'O processo é realizado manualmente e ainda não existe um sistema.', expectedResult:'A primeira versão deve atender ao fluxo principal com uma solução simples.', preserve:'Preservar os dados de origem e permitir evolução futura.' }
  ];
}());
